### PR TITLE
Add web plugin

### PR DESCRIPTION
**Pull request by bubenkoff**
This adds web plugin
also puts dependencies to a separate file

[Review on Reviewable](https://reviewable.io/reviews/scrapinghub/docker-devpi/8)

### CODE REVIEW

**Comment by ediskandarov-cur** [comment]
Can you freeze requirements?

**Comment by bubenkoff** [comment]
with you help - would love to :)

On 21 March 2016 at 15:35, Eduard Iskandarov notifications@github.com
wrote:

> Can you freeze requirements?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/scrapinghub/docker-devpi/pull/8#issuecomment-199317523

## 

Anatoly Bubenkov

**Comment by bubenkoff** [comment]
ah, sorry, i misunderstood
i actually didn't want to freeze because it only causes issues, instead,
because devpi is quite stable, you could rebuild an image and get all latest

On 21 March 2016 at 15:36, Anatoly Bubenkov bubenkoff@gmail.com wrote:

> with you help - would love to :)
> 
> On 21 March 2016 at 15:35, Eduard Iskandarov notifications@github.com
> wrote:
> 
> > Can you freeze requirements?
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/scrapinghub/docker-devpi/pull/8#issuecomment-199317523
> 
> ## 
> 
> Anatoly Bubenkov

## 

Anatoly Bubenkov

**Comment by ediskandarov-cur** [comment]
I see, but it will be good to have consistent docker tags.

**Comment by bubenkoff** [comment]
then we could make the ARG at least?

On 21 March 2016 at 17:16, Eduard Iskandarov notifications@github.com
wrote:

> I see, but it will be good to have consistent docker tags.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/scrapinghub/docker-devpi/pull/8#issuecomment-199361806

## 

Anatoly Bubenkov

**Pull request closed without merging**
